### ISSUE TITLE
Google analytics implementering i UE4 aka det finnes løsning for det

### ISSUE THREAD

**Issue by NasteX** [NasteX/VR---DemoVersjon#28]
https://forums.unrealengine.com/showthread.php?94807-Google-Analytics-Provider-Plugin-for-iOS-amp-Android

https://sellfy.com/p/oLbJ/

**Comment by NasteX** [comment]
Veldig positive anmeldelser av folk som har brukt det.

**Comment by haakong** [comment]
Teste ut prinsippielt:
-Innstallere plugin
-Lagre data til plug-in.  Lagre hvilket rom man er i hvert 10 sekund
-Pushe data til Google Analytics
-Se data på Google Analytics dashboard

**Comment by NasteX** [comment]
https://forums.unrealengine.com/showthread.php?92022-Unreal-js  <--- Javascript

**Comment by NasteX** [comment]
https://forums.unrealengine.com/showthread.php?13509-Plugin-Http-s-REST-blueprintable-JSON-and-Parse-REST-API-manager-at-once-(VaRest)
